{
	"id": "CVE-2025-27556",
	"sourceIdentifier": "cve@mitre.org",
	"vulnStatus": "Awaiting Analysis",
	"published": "2025-04-02T13:15:44.373",
	"lastModified": "2025-04-02T22:15:19.367",
	"descriptions": [
		{
			"lang": "en",
			"value": "An issue was discovered in Django 5.1 before 5.1.8 and 5.0 before 5.0.14. The NFKC normalization is slow on Windows. As a consequence, django.contrib.auth.views.LoginView, django.contrib.auth.views.LogoutView, and django.views.i18n.set_language are subject to a potential denial-of-service attack via certain inputs with a very large number of Unicode characters."
		},
		{
			"lang": "es",
			"value": "Se descubrió un problema en Django 5.1 antes de 5.1.8 y 5.0 antes de 5.0.14. La normalización de NFKC es lenta en Windows. Como consecuencia, django.contrib.auth.views.loginview, django.contrib.auth.views.logoutview, y django.views.i18n.set_language están sujetos a un posible ataque de denegación de servicio a través de ciertas entradas con un número muy grande de caracteres Unicode."
		}
	],
	"references": [
		{
			"source": "cve@mitre.org",
			"url": "https://docs.djangoproject.com/en/dev/releases/security/"
		},
		{
			"source": "cve@mitre.org",
			"url": "https://groups.google.com/g/django-announce"
		},
		{
			"source": "cve@mitre.org",
			"url": "https://www.djangoproject.com/weblog/2025/apr/02/security-releases/"
		},
		{
			"source": "af854a3a-2127-422b-91ae-364da2661108",
			"url": "http://www.openwall.com/lists/oss-security/2025/04/02/2"
		}
	],
	"metrics": {
		"cvssMetricV31": [
			{
				"source": "cve@mitre.org",
				"type": "Secondary",
				"cvssData": {
					"version": "3.1",
					"vectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:C/C:N/I:N/A:L",
					"attackVector": "NETWORK",
					"attackComplexity": "LOW",
					"privilegesRequired": "NONE",
					"userInteraction": "NONE",
					"scope": "CHANGED",
					"confidentialityImpact": "NONE",
					"integrityImpact": "NONE",
					"availabilityImpact": "LOW",
					"baseScore": 5.8,
					"baseSeverity": "MEDIUM"
				},
				"exploitabilityScore": 3.9,
				"impactScore": 1.4
			}
		]
	},
	"weaknesses": [
		{
			"source": "cve@mitre.org",
			"type": "Secondary",
			"description": [
				{
					"lang": "en",
					"value": "CWE-770"
				}
			]
		}
	],
	"vcConfigurations": [
		{
			"nodes": [
				{
					"operator": "OR",
					"cpeMatch": [
						{
							"vulnerable": true,
							"criteria": "cpe:2.3:a:djangoproject:django:*:*:*:*:*:*:*:*",
							"matchCriteriaId": "",
							"versionStartIncluding": "5.0",
							"versionEndExcluding": "5.0.14"
						},
						{
							"vulnerable": true,
							"criteria": "cpe:2.3:a:djangoproject:django:*:*:*:*:*:*:*:*",
							"matchCriteriaId": "",
							"versionStartIncluding": "5.1",
							"versionEndExcluding": "5.1.8"
						}
					]
				}
			]
		}
	],
	"vcVulnerableCPEs": [
		"cpe:2.3:a:djangoproject:django:5.0.0:*:*:*:*:*:*:*",
		"cpe:2.3:a:djangoproject:django:5.0.10:*:*:*:*:*:*:*",
		"cpe:2.3:a:djangoproject:django:5.0.11:*:*:*:*:*:*:*",
		"cpe:2.3:a:djangoproject:django:5.0.13:*:*:*:*:*:*:*",
		"cpe:2.3:a:djangoproject:django:5.0.2:*:*:*:*:*:*:*",
		"cpe:2.3:a:djangoproject:django:5.0.3:*:*:*:*:*:*:*",
		"cpe:2.3:a:djangoproject:django:5.0.7:*:*:*:*:*:*:*",
		"cpe:2.3:a:djangoproject:django:5.0.8:*:*:*:*:*:*:*",
		"cpe:2.3:a:djangoproject:django:5.0.9:*:*:*:*:*:*:*",
		"cpe:2.3:a:djangoproject:django:5.0:*:*:*:*:*:*:*",
		"cpe:2.3:a:djangoproject:django:5.1.0:*:*:*:*:*:*:*",
		"cpe:2.3:a:djangoproject:django:5.1.1:*:*:*:*:*:*:*",
		"cpe:2.3:a:djangoproject:django:5.1.4:*:*:*:*:*:*:*",
		"cpe:2.3:a:djangoproject:django:5.1.5:*:*:*:*:*:*:*",
		"cpe:2.3:a:djangoproject:django:5.1.7:*:*:*:*:*:*:*",
		"cpe:2.3:a:djangoproject:django:5.1:*:*:*:*:*:*:*"
	]
}
